version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: currency-nginx
        depends_on:
            - php
        working_dir: /var/www/html
        volumes:
            - ./.docker/nginx/currency.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        ports:
            - '80:80'
        networks:
            - currency-network

    php:
        build:
            context: ./.docker/php
            args:
                USER: kozols
                GROUP: kozols
        container_name: currency-php
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        working_dir: /var/www/html
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        volumes:
            - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./:/var/www/html
        ports:
            - '9000:9000'
        expose:
            - '9000'
        networks:
            - currency-network

    postgres:
        image: postgres:alpine
        container_name: currency-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db:/var/lib/postgresql/data:rw
        ports:
            - '5432:5432'
        networks:
            - currency-network

    redis:
        image: redis:alpine
        container_name: currency-redis
        ports:
            - '6379:6379'
        networks:
            - currency-network

networks:
    currency-network:

volumes:
    db:
